// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTgA9qiHb89eb9iCU7o7pNq4X0PdOpSOk',
    appId: '1:584691722174:web:47c4afd7e7c21a9b96fbef',
    messagingSenderId: '584691722174',
    projectId: 'matchwiz-final-project',
    authDomain: 'matchwiz-final-project.firebaseapp.com',
    storageBucket: 'matchwiz-final-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHbBP3-sCz-cVUFj612YuHUg8e7MPzbDk',
    appId: '1:584691722174:android:fb3c3a4b982fa64096fbef',
    messagingSenderId: '584691722174',
    projectId: 'matchwiz-final-project',
    storageBucket: 'matchwiz-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMubUdF3fCtXwp-MqgbvPiokQAPo2fuEA',
    appId: '1:584691722174:ios:3047b1be2c09cc5196fbef',
    messagingSenderId: '584691722174',
    projectId: 'matchwiz-final-project',
    storageBucket: 'matchwiz-final-project.appspot.com',
    iosClientId: '584691722174-bno8p19f77655kdd035uqjg1it5jph66.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoryGame',
  );
}
